### ISSUE TITLE
Bayer 

### ISSUE THREAD

**Issue by Tinkerer-Zlosk** [adrhill/DitherPunk.jl#4]
In ordered.jl, there is in error in the bayer_matrix function, as the added integers are being included in the multiplication.

        bₙ₋₁ = bayer_matrix(n - 1)
        b = 4 * [(bₙ₋₁) (bₙ₋₁.+2); (bₙ₋₁.+3) (bₙ₋₁.+1)]

should be

        bₙ₋₁ = 4 * bayer_matrix(n - 1)
        b = [(bₙ₋₁) (bₙ₋₁.+2); (bₙ₋₁.+3) (bₙ₋₁.+1)]

bayer_matrix(1)  # Current
4×4 Array{Int64,2}:
  0   8   8  16
 12   4  20  12
 12  20   4  12
 24  16  16   8

fixed_bayer_matrix(1) # Fixed
4×4 Array{Int64,2}:
  0   8   2  10
 12   4  14   6
  3  11   1   9
 15   7  13   5

**Comment by adrhill** [comment]
Thanks a lot! :)
