### ISSUE TITLE
Decrease memory usage in tile_matrix

### ISSUE THREAD

**Issue by Tinkerer-Zlosk** [adrhill/DitherPunk.jl#8]
In the tile_matrix(h, w, mat) function in ordered.jl, the line `return repeat(mat, repeat_rows, repeat_cols)[1:h, 1:w] # trim to image dims`  is using twice the memory actually required for the returned matrix -- 'repeat' is creating one image in memory, and [1:h, 1:w] appears to be creating a 2nd image in memory. When the [1:h, 1:w] at the end of the line is removed, memory usage drops to half, and mean run time drops by 60%.

A 2nd possible issue is the argument order for this function. If a bang version was created, then the arguments should be (mat, h, w) instead of (h, w, mat).

Below is a listing that covers both of these issues. Aside from using less memory, it has about 20% less median run time.  I couldn't hit the 60% reduction; repeat's codebase is considerably faster than mine, but is also considerably more convoluted. I could not follow it.

`function tile_matrix(mat, h, w)
	new = Vector{eltype(mat)}(undef, h*w)
	new = reshape(new, h, w) 	
	h_mat, w_mat = size(mat)	
	
	for i = 1:w_mat, j = 1:h_mat
		new[j:h_mat:h, i:w_mat:w] .= mat[j,i]
	end
	return new
end`

**Comment by adrhill** [comment]
Hi Tinkerer-Zlosk,

thanks for your issue! I also took a stab at reducing the allocations:
```julia
using BenchmarkTools
using DitherPunk: bayer_matrix

# tile_matrix from 0.2.4
function tile_matrix1(mat, h, w)
    h_mat, w_mat = size(mat)
    repeat_rows = ceil(Int, h / h_mat)
    repeat_cols = ceil(Int, w / w_mat)
    return repeat(mat, repeat_rows, repeat_cols)[1:h, 1:w] # trim to image dims
end

# tile_matrix from 0.2.4 using view
function tile_matrix2(mat, h, w)
    h_mat, w_mat = size(mat)
    repeat_rows = ceil(Int, h / h_mat)
    repeat_cols = ceil(Int, w / w_mat)
    return view(repeat(mat, repeat_rows, repeat_cols), 1:h, 1:w) # trim to image dims
end

# Tinkerer-Zlosk's suggestion
function tile_matrix3(mat, h, w)
    new = Vector{eltype(mat)}(undef, h*w)
    new = reshape(new, h, w)
    h_mat, w_mat = size(mat)

    for i = 1:w_mat, j = 1:h_mat
        new[j:h_mat:h, i:w_mat:w] .= mat[j,i]
    end
    return new
end

# Matrix to be tiled
level = 2
bayer = bayer_matrix(level)
mat = bayer//(2^(2 * level + 2)) # 8×8 Matrix

# Output size
h = 1080
w = 1920
```
`tile_matrix2`, the modification of the original with `view` seems to be the most performant:
```julia-repl
julia> @benchmark tile_matrix1(mat, h, w)

BenchmarkTools.Trial: 
  memory estimate:  63.28 MiB
  allocs estimate:  4
  --------------
  minimum time:     9.060 ms (0.00% GC)
  median time:      13.206 ms (29.23% GC)
  mean time:        13.626 ms (30.88% GC)
  maximum time:     87.738 ms (87.42% GC)
  --------------
  samples:          367
  evals/sample:     1
```
```julia-repl
julia> @benchmark tile_matrix2(mat, h, w)

BenchmarkTools.Trial: 
  memory estimate:  31.64 MiB
  allocs estimate:  3
  --------------
  minimum time:     3.958 ms (0.00% GC)
  median time:      4.873 ms (0.00% GC)
  mean time:        6.200 ms (34.02% GC)
  maximum time:     84.604 ms (93.99% GC)
  --------------
  samples:          805
  evals/sample:     1
```
```julia-repl
julia> @benchmark tile_matrix3(mat, h, w)

BenchmarkTools.Trial: 
  memory estimate:  31.64 MiB
  allocs estimate:  4
  --------------
  minimum time:     9.581 ms (0.00% GC)
  median time:      11.371 ms (0.00% GC)
  mean time:        12.339 ms (19.60% GC)
  maximum time:     88.076 ms (86.99% GC)
  --------------
  samples:          405
  evals/sample:     1
```

**Comment by Tinkerer-Zlosk** [comment]
I can't believe that I didn't try 'view'! I'm glad you found a better fix
than mine.

Paul (aka Zlosk)
